version: '2.1'

services:
  wildfly:
    build: wildfly/.
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - '8080:8080'
      - '9990:9990'

  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: testdb
      MYSQL_USER: student
      MYSQL_PASSWORD: student
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "--silent"]
      timeout: 20s
      retries: 10
